### ISSUE TITLE
`missing field arguments` error while downloading

### ISSUE THREAD

**Issue by Umatriz** [Umatriz/nomi#21]
List of fixed verisons:

- [x] 1.20.*
- [x] 1.19.*
- [x] 1.18.*
- [x] 1.12.2

**Comment by nakidai** [comment]
I tested that versions above 1.12.2 download well, and versions 1.12.2 and below raise `missing field arguments` error

**Comment by Umatriz** [comment]
working on fix

**Comment by Umatriz** [comment]
fixed
