### ISSUE TITLE
tracking: Quality of life features

### ISSUE THREAD

**Issue by Umatriz** [Umatriz/nomi#40]
This issue tracks features that should be included in the 0.2.3 update.

- [x] #39 
- [x] #41
- [x] #42
- [x] #43
- [x] #44
- [x] #45
- [x] #47
- [x] #59

**Comment by nakidai** [comment]
> _<ins>tacking</ins>_: Quality of life features

Minro spelin miskate!!! :fire: :index_pointing_at_the_viewer: :index_pointing_at_the_viewer: :skull: :skull_and_crossbones: :skull: :fire:

**Comment by Umatriz** [comment]
> > _tacking_: Quality of life features
> 
> Minro spelin miskate!!! 🔥 🫵 🫵 💀 ☠️ 💀 🔥

ty
